title: DeepInsight-FS Package
description: The package has been tested on Ubuntu 18.10 with Matlab R2020a
theme: jekyll-theme-leap-day
show_downloads: "true"
github:
  zip_url: https://github.com/alok-ai-lab/deepinsight-fs/raw/master/archive/DeepInsight-FS_pkg.zip
  tar_url: https://github.com/alok-ai-lab/deepinsight-fs/raw/master/archive/DeepInsight-FS_pkg.tar.gz